[rewrite_local]
^https:\/\/api\.getmoshi\.app\/api\/v1\/licenses\/(?:me|activate|[^\/]+\/devices)(?:[\/?#]|$) url script-analyze-echo-response https://raw.githubusercontent.com/ttbug/qxddm/refs/heads/own/ms.js

[mitm]
hostname = api.getmoshi.app
